[package]
name = "erabu"
version = "0.1.0"
authors = ["SitiSchu <admin@sitischu.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.2.18"
serde_json = "1.0"
dirs = "2.0"
rand = "0.7"
